---
title: "Codebook"
author: "Alex Babicz"
date: "16.8.2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Feature Selection 

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ  
tGravityAcc-XYZ  
tBodyAccJerk-XYZ  
tBodyGyro-XYZ  
tBodyGyroJerk-XYZ  
tBodyAccMag  
tGravityAccMag  
tBodyAccJerkMag  
tBodyGyroMag  
tBodyGyroJerkMag  
fBodyAcc-XYZ  
fBodyAccJerk-XYZ  
fBodyGyro-XYZ  
fBodyAccMag  
fBodyAccJerkMag  
fBodyGyroMag  
fBodyGyroJerkMag  

The set of variables that were estimated from these signals are: 

*mean()*: Mean value  
*std()*: Standard deviation  
*mad()*: Median absolute deviation   
*max()*: Largest value in array  
*min()*: Smallest value in array  
*sma()*: Signal magnitude area  
*energy()*: Energy measure. Sum of the squares divided by the number of values.   
*iqr()*: Interquartile range   
*entropy()*: Signal entropy  
*arCoeff()*: Autorregresion coefficients with Burg order equal to 4  
*correlation()*: correlation coefficient between two signals  
*maxInds()*: index of the frequency component with largest magnitude  
*meanFreq()*: Weighted average of the frequency components to obtain a mean frequency  
*skewness()*: skewness of the frequency domain signal   
*kurtosis()*: kurtosis of the frequency domain signal  
*bandsEnergy()*: Energy of a frequency interval within the 64 bins of the FFT of each window.  
*angle()*: Angle between to vectors.  

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean  
tBodyAccMean  
tBodyAccJerkMean  
tBodyGyroMean  
tBodyGyroJerkMean  

The complete list of variables of each feature vector is available in the raw dataset.

## Variables created during the data preperation
*activities*: data frame (6x2) with all 6 measured activities (names in the second column)  
*features*: data frame (561x2) with all 561 measured features (e.g. tBodyAcc on the three different axis (mean and sd values))  
*trainSet*: data frame (7352x561) with measurements on all the features for testing purposes  
*testSet*: data frame (2947x561) with measurements on all the features used for future testing  
*mergedSet*: data frame (10299x561) that is a combination of the training and test set  
*trainMoves*: data frame (7352x1) with the integer that represents the activity (one of 6 from *activities*) for the training set  
*testMoves*: data frame (2947x1) with the integer that represents the activity (one of 6 from *activities*) for the test set  
*mergedMoves*: data frame (10299x561) that is a combination of the activity representation for the training and test set  
*trainPerson*: data frame (7352x1) with the IDs for each individual within the training set  
*testPerson*: data frame (2947x1) with the IDs for each individual within the test set  
*mergedPerson*: data frame (10299x561) that is a combination of IDs for the training and test set  
*mergedSetFiltered*: data frame (10299x88) which is the mergedSet data frame with only the measurements that include measures on mean and sd data  
*tidySummarizedData*: data frame (10299x88) with the average (mean) values for all the measurements of *mergedSetFiltered*